version: '3'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: jua-app-prod
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=${APP_URL}
      - DB_CONNECTION=mysql
      - DB_HOST=rwcoso0sggk8ggsg448w440s
      - DB_PORT=3306
      - DB_DATABASE=default
      - DB_USERNAME=mysql
      - DB_PASSWORD=TH3gregloyal89
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-null}
      - MAIL_MAILER=${MAIL_MAILER:-smtp}
      - MAIL_HOST=${MAIL_HOST:-mailhog}
      - MAIL_PORT=${MAIL_PORT:-1025}
      - MAIL_USERNAME=${MAIL_USERNAME:-null}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-null}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-null}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@jua.twunhu.app}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-Jua}
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_HOST=${PUSHER_HOST}
      - PUSHER_PORT=${PUSHER_PORT}
      - PUSHER_SCHEME=${PUSHER_SCHEME}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
      - SESSION_DOMAIN=${SESSION_DOMAIN:-jua.twunhu.app}
      - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS:-jua.twunhu.app}
    volumes:
      - jua-storage:/var/www/html/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-check.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      - traefik.http.routers.jua-app.rule=Host(`jua.twunhu.app`)
      - traefik.http.routers.jua-app.entrypoints=https
      - traefik.http.routers.jua-app.tls=true
      - traefik.http.routers.jua-app.tls.certresolver=letsencrypt
      - traefik.http.services.jua-app.loadbalancer.server.port=80
    ports:
      - "80:80"
    networks:
      - coolify

networks:
  coolify:
    external: true
  jua-network:
    driver: bridge

volumes:
  jua-storage:
    driver: local
